CREATE TABLE patient_login (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	Firstname TEXT NOT NULL,
	Lastname TEXT NOT NULL,
    DOB DATE NOT NULL,
    Gender TEXT NOT NULL,
    IDno CHAR(13) NOT NULL,
    ConNo CHAR(12) NOT NULL,
    Email VARCHAR NOT NULL,
    LangPref TEXT NOT NULL,
	Pwd VARCHAR NOT NULL
);